### ISSUE TITLE
Multi access to SQL

### ISSUE THREAD

**Issue by krzysrok** [TimSVector/vc_scripts_submodule#3]
![image](https://github.com/user-attachments/assets/c03c5dcd-88c0-46b1-9135-08dfb101741c)
Did you faced such issue during creation of parallelization script? (not related to your script ;))
Maybe you have any idea how to overcame it?

**Comment by TimSVector** [comment]
That part of the parallel work is handled inside of VectorCAST so we don’t worry about when building in parallel.

**Comment by krzysrok** [comment]
Parallelization in VectorCast is handled form which version?
2023.7 do not have such option I guess?

**Comment by TimSVector** [comment]
By using 2019SP3 and above, you have access to parallel build-execute capabilities.  We either use Jenkins to build-execute in parallel, or a python script using Threads to accomplish that.

Tim

**Comment by krzysrok** [comment]
I mean some tools have such features build in the tool like compilers. Just additional parameter -j 4 will enable parallelization on 4 threads (much more faster compilation). 
But I guess this is not the case so we need to use real threads in jenkins/python.

Thanks for clarification :)

**Comment by TimSVector** [comment]
There are lots of different parallel build options for QA Project and Unit Test, but as of right now, there’s nothing in the product directly that support parallel build-execute of a unit test environment, without external scripts.

You should be asking ***@***.******@***.***>.  This will allow the correct support engineer to assist you directly with your VectorCAST issues.  We can doing a lot of things to help customers out.
